env: GHCVER=7.8.4

sudo: required
language: c
cache:
  apt: true
  directories:
    - $HOME/.opam
    
install:
  - sudo add-apt-repository --yes ppa:avsm/ppa
  - sudo apt-get update && sudo apt-get install -y opam
  - opam init -y && eval $(opam config env) && opam config var root
  - travis_wait opam install -y coq.8.6

script:
    - cd Coq
    - make
